### PR TITLE
DoH cleanup & tests

### PR DESCRIPTION
**Pull request by GXTX**
Add a new service provider (Mozilla via Cloudflare), cleanup a little bit of the code.
Adds a new test case looking for a positive DNS response from all 3 providers.

### CODE REVIEW

**Comment by lordelph** [comment]
Thanks for this - I really should get this branch finished!

My only reservation with this PR is that the DNSOverHTTPS tests have external dependencies - they can fail due to reasons outside of the code's control. One approach would be to use Prophecy to mock an HTTP client which returns canned JSON responses.

I'll merge the PR anyway and adjust the tests before merging this 'polish' branch into master - might be later in the week before can I do that. Feel free to submit another PR for that if you like!

Thanks again

Paul

**Comment by GXTX** [comment]
Cheers for that, glad to see you haven't completely abandoned the project.

The reason I wrote the tests like that (I have a couple more ready to push but I'm sure you'd be alot better suited for that!) is I wanted to make sure the real servers actually produced the responses required, even though it's (should be...) handled correctly in code now.

I did notice I didn't write a catch in case Guzzle gives anything but a valid 200 response. I have a version local that fixes this and removes the `checkError()` function and incorporates it in with `get()`, would you like a PR for that?

**Comment by lordelph** [comment]
I think what I'll do make it so those tests can be executed separately, e.g. `composer test-dns-integration` so that the continuous integration has no external dependency. 

As for the extra PR, go for it :)

**Comment by lordelph** [comment]
I've made it so that integration tests can be tagged with a phpunit `@group integration` annotation, and these are excluded from the usual `composer test` suite executed by travis. Running `composer test-all` will run all tests.

**Pull request merged**
